### ISSUE TITLE
need image size for bash make_video.sh

### ISSUE THREAD

**Issue by TheCompAce** [zeruniverse/fast-artistic-videos#11]
This is more of a warning.

when running
`bash make_video.sh *example.mp4*`
you will need to supply the converted image's size, or else the script will not find the correct file.

**Comment by zeruniverse** [comment]
let me check

**Comment by zeruniverse** [comment]
so if you follow the steps, you don't need to supply the size. You most likely put the size info into file names in previous steps...

**Comment by zeruniverse** [comment]
closed due to no response.
