### ISSUE TITLE
Feasible to use spynet for optical-flow?

### ISSUE THREAD

**Issue by tkoham** [zeruniverse/fast-artistic-videos#4]
I'm trying to get the optical flow process onto the gpu, and the closest to drop-in replacement for deepflow that I can find seems to be a script using 

    https://github.com/anuragranj/spynet

you can make it spit out .flo files pretty easily but I'm not familiar enough with this project (or lua, really) to know if I'm going on a wild goose-chase here.

**Comment by zeruniverse** [comment]
As long as you can generate .flo between two frames, it's OK.

Knowledge about Lua is not necessary. You only need to modify *opt_flow.sh* and *run-deepflow.sh* to make it work.

**Comment by tkoham** [comment]
Ok awesome. Might throw a fork up of this with gpu acceleration when/if I get it working

**Comment by zeruniverse** [comment]
Welcome! :)
