### ISSUE TITLE
non-coder having issues running repo

### ISSUE THREAD

**Issue by sdewitt108** [zeruniverse/fast-artistic-videos#9]
When I run the first line - "bash fast_stylize.sh *example.mp4* *models/starry_night.t7*"

I get back an error saying that the "models" directory can not be found, even though it is at the root of this directory. Being a non-coder I am having trouble figuring out how to proceed.

Here is the actual error that I get -

"ERROR: Could not load model from models/starry_night.t7	
You may need to download the pretrained models by running	
bash models/download_style_transfer_models.sh	
  File "<string>", line 1
    print(1527885997.N - 1527885996.N)"

But that "models" directory IS there with the correct models inside. I hope this makes sense and sorry if it does not, I am groping in the dark a bit here.

Thanks

Sam

**Comment by bafonso** [comment]
I'm getting the same error and the reason is that the download script is broken.

**Comment by zeruniverse** [comment]
Hi guys,

Sorry for the late reply. As you can see this is a very old project… (And I didn’t watch it). I won’t feel surprised if something not working.

I would suggest installing distro http://torch.ch/docs/getting-started.html

**Comment by zeruniverse** [comment]
@sdewitt108 @bafonso 

The downloading script is from 
https://github.com/jcjohnson/fast-neural-style/

Please go there and see if the model is still available in that repo. If not, you’ll need to retrain the base model following that repo...

**Comment by bafonso** [comment]
I believe the problem is that curl -O does not work anymore, but wget worked.

**Comment by zeruniverse** [comment]
Cool! Feel free to submit a pull request.
